/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kingaspx.firebase.menu;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import static com.kingaspx.firebase.util.Common.initFirebase;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author mario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static String sumApofloiosh,sumTomatopoltos;
    public Menu() {
        initComponents();
        initFirebase();
        
        
        
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        databaseRefe = database.getReference("count");
        databaseRefe.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                    sumApofloiosh= ds.child("countapofloiosh").getValue().toString();
                    }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
        });
        
        
        databaseRefe.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                    sumTomatopoltos= ds.child("countTomatopoltos").getValue().toString();
                    }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
        });
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        onomateponymoTextField = new javax.swing.JTextField();
        ptTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eisagwghSteixeionButton = new javax.swing.JButton();
        ksenesYlesLabel = new javax.swing.JLabel();
        PoiotikaElatomataLabel = new javax.swing.JLabel();
        AkaireoiKarpoiLabel = new javax.swing.JLabel();
        eisagwghDedomenonButton = new javax.swing.JButton();
        YpologismosPosostonButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ΣΤΟΙΧΕΙΑ ΠΑΡΑΓΩΓΟΥ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ΟΝΟΜΑΤΕΠΩΝΥΜΟ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ΠΤ");

        eisagwghSteixeionButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eisagwghSteixeionButton.setText("Εισαγωγη");
        eisagwghSteixeionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eisagwghSteixeionButtonActionPerformed(evt);
            }
        });

        synolikodeigmaLabel.setForeground(new java.awt.Color(51, 51, 51));
        synolikodeigmaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        synolikodeigmaLabel.setText("0");
        synolikodeigmaLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        akaireosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        akaireosLabel.setText("0");
        akaireosLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        spasmenesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spasmenesLabel.setText("0");
        spasmenesLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        poiotikaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poiotikaLabel.setText("0");
        poiotikaLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ksenesYlesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ksenesYlesLabel.setText("0");
        ksenesYlesLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PoiotikaElatomataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PoiotikaElatomataLabel.setText("0");
        PoiotikaElatomataLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AkaireoiKarpoiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AkaireoiKarpoiLabel.setText("0");
        AkaireoiKarpoiLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BrixLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BrixLabel.setText("0");
        BrixLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eisagwghDedomenonButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eisagwghDedomenonButton.setText("Εισαγωγή Δεδομένων");
        eisagwghDedomenonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eisagwghDedomenonButtonActionPerformed(evt);
            }
        });

        YpologismosPosostonButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        YpologismosPosostonButton.setText("Υπολογισμός Ποσοστών");
        YpologismosPosostonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YpologismosPosostonButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Βάση");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Συνολικό Δείγμα");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Ακαιρεος Καρπός");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Σπασμένες");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Ποιοτικά Ελλατόματα");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Ξενες Υλες");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Ποιοτικά Ελλατόματα");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Ακαίρεος Καρπός");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Brix");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("ΑΠΟΦΛΕΙΩΣΗ");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("ΤΟΜΑΤΟΠΟΛΤΟΣ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ksenesYlesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(PoiotikaElatomataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BrixLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(poiotikaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel16)
                .addGap(175, 175, 175)
                .addComponent(jLabel17)
                .addGap(150, 150, 150)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(synolikodeigmaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eisagwghDedomenonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eisagwghSteixeionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(onomateponymoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(AkaireoiKarpoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(akaireosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(128, 128, 128)
                                                    .addComponent(spasmenesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(YpologismosPosostonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onomateponymoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eisagwghSteixeionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synolikodeigmaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akaireosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spasmenesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poiotikaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ksenesYlesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PoiotikaElatomataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AkaireoiKarpoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eisagwghDedomenonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YpologismosPosostonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eisagwghSteixeionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eisagwghSteixeionButtonActionPerformed
        // TODO add your handling code here:
        eisagoghStoixeion();
        
    }//GEN-LAST:event_eisagwghSteixeionButtonActionPerformed

    private void eisagwghDedomenonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eisagwghDedomenonButtonActionPerformed
        // TODO add your handling code here:
        eisagoghDedomenonFrame eisagogh_DedomenonFrame= new eisagoghDedomenonFrame();
        eisagogh_DedomenonFrame.setVisible(true);
    }//GEN-LAST:event_eisagwghDedomenonButtonActionPerformed
Paragogos paragogos;
    private void YpologismosPosostonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YpologismosPosostonButtonActionPerformed
        double sum=0.0;
        
        paragogos = new Paragogos();
        
        double akaireos, spasmenes, poiotika, synoliko;
        akaireos=Double.parseDouble(akaireosLabel.getText());
        
        
        spasmenes=Double.parseDouble(spasmenesLabel.getText());
        poiotika =Double.parseDouble(poiotikaLabel.getText());
        synoliko = Double.parseDouble(synolikodeigmaLabel.getText());
        sum= (((synoliko-(akaireos+spasmenes+poiotika))/synoliko ))*100 ;
        BigDecimal bd = new BigDecimal(sum).setScale(2, RoundingMode.HALF_UP);
        double newInput = bd.doubleValue();
        String summ = String.valueOf(newInput);
        paragogos.setPosostoKsenesYles(summ);
        ksenesYlesLabel.setText( summ);
        
        double PE, AK;
        AK=(akaireos/(akaireos+spasmenes+poiotika))*100;
        BigDecimal bd2 = new BigDecimal(AK).setScale(2, RoundingMode.HALF_UP);
        double newInput2 = bd2.doubleValue();
        summ=String.valueOf(newInput2);
        
        paragogos.setPosostoSkaireoi(summ);
        AkaireoiKarpoiLabel.setText(summ);
        
        PE=(poiotika/(akaireos+spasmenes+poiotika))*100;
        BigDecimal bd3 = new BigDecimal(PE).setScale(2, RoundingMode.HALF_UP);
        double newInput3 = bd3.doubleValue();
        
        
        summ=String.valueOf(newInput3);
        paragogos.setPosostoSoiotika(summ);
        PoiotikaElatomataLabel.setText(summ);
        
        paragogos.setBrix(BrixLabel.getText());
        
        
        
        
        
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        
        
        
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("akaireoiKarpoi");
        databaseRefe
        .setValue(paragogos.getPosostoSkaireoi(), new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        
        
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("ksenesYles");
        databaseRefe
        .setValue(paragogos.getPosostoKsenesYles(), new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("poiotika");
        databaseRefe
        .setValue(paragogos.getPosostoSoiotika(), new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("brix");
        databaseRefe
        .setValue(paragogos.getBrix(), new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        
        
        
        paragogos.setFlag("Yes");
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("flag");
        databaseRefe
        .setValue(paragogos.getFlag(), new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        
        
                
                
                
                
                
                
                
                
                
        
        
        

        
// TODO add your handling code here:
    }//GEN-LAST:event_YpologismosPosostonButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("typoksefortomatos");
        databaseRefe
        .setValue("1", new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        
        databaseRefe = database.getReference("count");
        databaseRefe.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                    sumApofloiosh= ds.child("countapofloiosh").getValue().toString();
                    }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
        }); 
        
        
        int summ=Integer.parseInt(sumApofloiosh);
        summ=summ+1;
        sumApofloiosh=String.valueOf(summ);
        databaseRefe.child("countapofloiosh").setValue(sumApofloiosh, new DatabaseReference.CompletionListener() {
                        @Override
                        public void onComplete(DatabaseError de, DatabaseReference dr) {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    });
        
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        databaseRefe = database.getReference("stoixeia").child(ptTextField.getText()).child("paragogos").child("typoksefortomatos");
        //2=tomatopoltos and 1= apofloiosh
        databaseRefe
        .setValue("2", new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                
            }
        });
        
        databaseRefe = database.getReference("count");
        databaseRefe.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                    sumApofloiosh= ds.child("countTomatopoltos").getValue().toString();
                    }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
        }); 
        
        
        int summ=Integer.parseInt(sumTomatopoltos);
        summ=summ+1;
        sumTomatopoltos=String.valueOf(summ);
        databaseRefe.child("countTomatopoltos").setValue(sumApofloiosh, new DatabaseReference.CompletionListener() {
                        @Override
                        public void onComplete(DatabaseError de, DatabaseReference dr) {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    });
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AkaireoiKarpoiLabel;
    public static final javax.swing.JLabel BrixLabel = new javax.swing.JLabel();
    private javax.swing.JLabel PoiotikaElatomataLabel;
    private javax.swing.JButton YpologismosPosostonButton;
    public static final javax.swing.JLabel akaireosLabel = new javax.swing.JLabel();
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton eisagwghDedomenonButton;
    private javax.swing.JButton eisagwghSteixeionButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel ksenesYlesLabel;
    private javax.swing.JTextField onomateponymoTextField;
    public static final javax.swing.JLabel poiotikaLabel = new javax.swing.JLabel();
    private javax.swing.JTextField ptTextField;
    public static final javax.swing.JLabel spasmenesLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel synolikodeigmaLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

   
    public static void eisagoghData(){
         NoumeraDeigmatos noumeraDeigmatos = new NoumeraDeigmatos();
        
        synolikodeigmaLabel.setText(noumeraDeigmatos.getSynolikodeigma());
        akaireosLabel.setText(noumeraDeigmatos.getAkaireoskarpos());
        spasmenesLabel.setText(noumeraDeigmatos.getSpasmenes());
        poiotikaLabel.setText(noumeraDeigmatos.getPoiotikaelatomata());
        BrixLabel.setText(noumeraDeigmatos.getBrix());
        
        
            
           
        
        
    
    }
    
    DatabaseReference databaseRefe;
        
        private void eisagoghStoixeion(){
            
            
            
            
            databaseRefe= FirebaseDatabase.getInstance().getReference("stoixeia").child(ptTextField.getText()).child("paragogos");
            databaseRefe.addValueEventListener(new  ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                   String name = ds.child("name").getValue().toString();
                   onomateponymoTextField.setText(name);
                    
                   String pt = ds.child("pt").getValue().toString();
                   ptTextField.setText(pt);
                   
                   String akaireoi = ds.child("akaireoiKarpoi").getValue().toString();
                   AkaireoiKarpoiLabel.setText(akaireoi);
                   
                   String ksenesYles = ds.child("ksenesYles").getValue().toString();
                   ksenesYlesLabel.setText(ksenesYles);
                   
                   String poiotika = ds.child("poiotika").getValue().toString();
                   PoiotikaElatomataLabel.setText(poiotika);
                   
                   String brix = ds.child("brix").getValue().toString();
                   BrixLabel.setText(brix);
                   
                   
                   
                   String fla = ds.child("flag").getValue().toString();
                   if(fla.equals("Yes")){
        
                        YpologismosPosostonButton.setEnabled(false);
                 }
                   else{
                       YpologismosPosostonButton.setEnabled(true);
                   }
                   
                   
                   
                }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
        }
    


}

